### ISSUE TITLE
Test failure with Uncode v15.0

### ISSUE THREAD

**Issue by thundergnat** [coke/p6-uni#9]
Now that Moar and Rakudo have moved to Unicode V15.0 one of the tests is failing:

```
test-run(q:to/EOUT/, '-n', 'stroke', 'dotl', 'modifier');
    ᶡ - U+001DA1 - MODIFIER LETTER SMALL DOTLESS J WITH STROKE [Lm]
    EOUT
```
Now fails because 

`𐞘 - U+010798 - MODIFIER LETTER SMALL DOTLESS J WITH STROKE AND HOOK [Lm]`

was added in Unicode V14.0.

May need to make the test Unicode version aware. (Conveniently the variable Unicode.version was added recently too.)

**Comment by coke** [comment]
Thanks for the report. I did what I think is the least clever thing to support this change in v15 - Use the Unicode class if it exists to check the version is recent enough, and if it doesn't exist, it's not, and check for the output based on the version.

I didn't have to stick with this sample, but this fix was straightforward.
